version: "3.3"
services:
  # Metrics store
  influxdb:
    # 21/03/15 - DB V2 구조 변경으로 기존 버전 연결 문제 발생: 1.8.4 버전으로 고정해서 처리, 향후 Influx관련 코드를 v2에 맞도록 처리할 필요 있음.
    image: influxdb:1.8.4
    container_name: etri_influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb

  # Metrics UI
  grafana:
    image: grafana/grafana
    container_name: etri_grafana
    user: "1000"
    ports:
      - "3100:3000"
    depends_on:
      - influxdb
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

  # Trace store and UI
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: etri_jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  # CB-RESTAPIGW SERVICE
  cb-restapigw:
    build:
      context: ./restapigw
    container_name: etri_apigw
    volumes:
      - ./restapigw/conf:/app/conf
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - jaeger