version: "3.3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    ports:
      - "3100:3000"
    depends_on:
      - influxdb
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  # Fake API
  fake_api:
    image: jaxgeller/lwan
    container_name: fake_api
    volumes:
      - ./data/lwan:/lwan/wwwroot
    ports:
      - "8100:8080"

  # CB-SPIDER
  cb-spider:
    build:
      context: ./cb-spider
    container_name: cb-spider
    ports:
      - "1024:1024"

  # CB-TUMBLEBUG
  cb-tumblebug:
    build:
      context: ./cb-tumblebug
    container_name: cb-tumblebug
    ports:
      - "1323:1323"
    depends_on:
      - cb-spider