version: "3.3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "1000"
    ports:
      - "3100:3000"
    depends_on:
      - influxdb
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  # CB-SPIDER
  cb-spider:
    image: cloudbaristahub/cb-spider:v0.1-20200319
    container_name: cb-spider
    ports:
      - "1024:1024"
    volumes:
      - ./data/cb-spider:/root/go/src/github.com/cloud-barista/cb-spider/meta_db/dat

  # CB-TUMBLEBUG
  cb-tumblebug:
    image: cloudbaristahub/cb-tumblebug:v0.1-20200313
    container_name: cb-tumblebug
    ports:
      - "1323:1323"
    volumes:
      - ./data/cb-tumblebug:/app/meta_db/dat
    environment:
      - SPIDER_URL=http://localhost:8000/spider
    depends_on:
      - cb-spider

  # CB-RESTAPIGW
  cb-restapigw:
    build:
      context: ./cb-restapigw
    container_name: cb-restapigw
    ports:
      - "8000:8000"
    depends_on:
      - influxdb
      - jaeger
      - cb-spider
      - cb-tumblebug