global:
  scrape_interval:     10s
  evaluation_interval: 10s
#  external_labels:
#    monitor: 'cbrestapigw'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  #- job_name: 'prometheus'
  #  static_configs:
  #    - targets: ['prometheus:9090']
  - job_name: 'cbrestapigw'
    scrape_interval: 1s
    static_configs:
      # docker-compose에 `extra_hosts`로 등록된 host 의 localhost 호출
      - targets: ['morrishost:9000']